version: '3.9'
services:
    api:
        image: ghcr.io/c-bv/tzf-api:main
        env_file:
            - .env
        restart: unless-stopped
        labels:
            - traefik.enable=true
            - traefik.http.routers.tzf-api.rule=Host(`dev-api.c-bv.dev`)
            - traefik.http.routers.tzf-api.entrypoints=websecure
            - traefik.http.services.tzf-api.loadbalancer.server.port=5000
        expose:
            - 5000

networks:
    default:
        name: traefik
        external: true