version: '3.9'
services:
    api:
        image: ghcr.io/c-bv/tzf-api:main
        restart: unless-stopped
        expose:
            - 5000
        networks:
            - nginx-proxy

networks:
    nginx-proxy:
        external: true
